/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emart.gui;

import emart.dao.OrderDAO;
import emart.dao.ProductsDAO;
import emart.pojo.ProductsPojo;
import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPTable;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author WELCOME
 */
public class BillingFrame extends javax.swing.JFrame {

         ArrayList<ProductsPojo> al = new ArrayList<>();
        double grTotal = 0.0;
        DefaultTableModel tm;

        public BillingFrame() {
            initComponents();
            
             try {
                        ProductsDAO.inactiveExpiredProducts();   // 👈 EXPIRED PRODUCTS BLOCKED
                 }
             catch (SQLException ex)
             {
                JOptionPane.showMessageDialog(null,"Failed to disable expired products: " + ex.getMessage(),"Error", JOptionPane.ERROR_MESSAGE);
             }
            this.setLocationRelativeTo(this);
            jtProducts.setRowHeight(30);
            tm = (DefaultTableModel) jtProducts.getModel();
            txtProductId.requestFocus();
            
            // click listener to remove item
            jtProducts.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jtProductsMouseClicked(evt);
                }
            });
        }
        private void jtProductsMouseClicked(java.awt.event.MouseEvent evt) {
        int row = jtProducts.getSelectedRow();
            if (row == -1) return;
            int choice = JOptionPane.showConfirmDialog(null,
                    "Do you want to remove this item from the cart?",
                    "Remove Item", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                double itemTotal = (double) jtProducts.getValueAt(row, 7);
                grTotal -= itemTotal;
                tm.removeRow(row);
                al.remove(row);
                lblGrandTotal.setText("Total: " + grTotal);
                JOptionPane.showMessageDialog(null, "Item removed from cart.");
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGenerateBill = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProducts = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProductId = new javax.swing.JTextField();
        lblGrandTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGenerateBill.setBackground(new java.awt.Color(215, 0, 0));
        btnGenerateBill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerateBill.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateBill.setText("Generate Bill");
        btnGenerateBill.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGenerateBill.setContentAreaFilled(false);
        btnGenerateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateBillActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerateBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, 150, 41));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setBackground(new java.awt.Color(216, 0, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setForeground(java.awt.Color.white);
        btnLogout.setText("LogOut");
        btnLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.setContentAreaFilled(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 50, 108, 40));

        btnBack.setBackground(new java.awt.Color(197, 0, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(java.awt.Color.white);
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 50, 108, 40));

        jtProducts.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Product Price", "Our Price", "Product Company", "Quantity", "Tax", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtProducts);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1120, 440));

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Billing Options");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 280, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Id");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 120, 30));

        txtProductId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtProductId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 190, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 1156, 580));

        lblGrandTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGrandTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblGrandTotal.setText("total :");
        jPanel1.add(lblGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 620, 151, 32));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnGenerateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateBillActionPerformed
                                                                                                                               
        if (al.isEmpty()) {
            JOptionPane.showMessageDialog(null, 
                "Cart is empty! Add items first.", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String ordId = OrderDAO.getNextOrderId();
            boolean orderSaved = OrderDAO.addOrder(al, ordId);

            if (!orderSaved) {
                JOptionPane.showMessageDialog(null, 
                    "Failed to save order to DB.", 
                    "DB Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            boolean stockUpdated = ProductsDAO.updateStocks(al);
            if (!stockUpdated) {
                JOptionPane.showMessageDialog(null, 
                    "Order saved but stock update failed!", 
                    "DB Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String billsDir = "E:\\Bills\\";
            File dir = new File(billsDir);
            if (!dir.exists()) dir.mkdirs();

            String billId = ordId + "_" + System.currentTimeMillis();
            String filePath = billsDir + billId + ".pdf";

            Document doc = new Document();
            FileOutputStream fos = null;

            try {
                fos = new FileOutputStream(filePath);
                PdfWriter.getInstance(doc, fos);
                doc.open();

                // ---------- LOGO SAFE LOADING ----------
                try {
                    String logoPath = "E:\\Bills\\logo.png";
                    File f = new File(logoPath);

                    if (f.exists()) {
                        com.itextpdf.text.Image logo = com.itextpdf.text.Image.getInstance(logoPath);
                        logo.scaleAbsolute(120, 80);
                        logo.setAlignment(Element.ALIGN_CENTER);
                        doc.add(logo);
                    }
                } catch (Exception e) {
                    // ignore but DO NOT STOP PDF
                }

                // ---------- HEADER ----------
                Paragraph header = new Paragraph("\n EMart Supermarket Billing System\n\n");
                header.setAlignment(Element.ALIGN_CENTER);
                doc.add(header);

                Paragraph line = new Paragraph("--------------------------------------------------------------------\n");
                doc.add(line);

                Paragraph details = new Paragraph(
                    "Bill ID : " + billId +
                    "\nDate   : " + new java.util.Date() +
                    "\nCashier: admin" +
                    "\nTotal  : Rs. " + String.format("%.2f", grTotal) + "\n\n"
                );
                doc.add(details);

                // -------- TABLE --------
                PdfPTable table = new PdfPTable(8);
                table.addCell("Product ID");
                table.addCell("Name");
                table.addCell("Price");
                table.addCell("Our Price");
                table.addCell("Company");
                table.addCell("Qty");
                table.addCell("Tax %");
                table.addCell("Sub Total");

                for (ProductsPojo p : al) {
                    table.addCell(p.getProductId());
                    table.addCell(p.getProductName());
                    table.addCell(String.valueOf(p.getProductPrice()));
                    table.addCell(String.valueOf(p.getOurPrice()));
                    table.addCell(p.getProductCompany());
                    table.addCell(String.valueOf(p.getQuantity()));
                    table.addCell(String.valueOf(p.getTax()));
                    table.addCell(String.valueOf(p.getTotal()));
                }

                doc.add(table);
                doc.add(line);

                Paragraph footer = new Paragraph("\nThank You for Shopping with eMart!\n\n");
                footer.setAlignment(Element.ALIGN_CENTER);
                doc.add(footer);

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, 
                    "PDF Error: " + ex.getMessage(), 
                    "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            } finally {
                try {
                    if (doc.isOpen()) doc.close();
                    if (fos != null) fos.close();
                } catch (Exception e) {}
            }

            // OPEN PDF
            Runtime.getRuntime().exec(new String[]{"cmd", "/c", "start", "", filePath});

            JOptionPane.showMessageDialog(null, 
                "Order of Rs " + String.format("%.2f", grTotal) + 
                "/- created successfully & Bill Generated.");

            this.dispose();
            new ViewOrdersFrame().setVisible(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, 
                "DB Error: " + ex.getMessage(), 
                "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }    catch (IOException ex) {
                 Logger.getLogger(BillingFrame.class.getName()).log(Level.SEVERE, null, ex);
             }


    }//GEN-LAST:event_btnGenerateBillActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        LoginFrame login=new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

            ReceptionistOptionFrame roframe = new ReceptionistOptionFrame();
            roframe.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtProductIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductIdActionPerformed
        if(txtProductId.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Plese enter product Id","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        loadItemList(txtProductId.getText().trim());
    }//GEN-LAST:event_txtProductIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
          ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BillingFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenerateBill;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtProducts;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JTextField txtProductId;
    // End of variables declaration//GEN-END:variables

   
    private void loadItemList(String pid) {
        try {
            ProductsPojo p = ProductsDAO.getProductDetails(pid);

            if (p.getProductId() == null) {
                JOptionPane.showMessageDialog(null, "Product not found in stock!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int availableQty = p.getQuantity();
            if (availableQty == 0) {
                JOptionPane.showMessageDialog(null, "Product is out of stock!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String qtyStr = JOptionPane.showInputDialog(null,
                    "Enter quantity for " + p.getProductName() + " (Available: " + availableQty + ")", "Quantity",
                    JOptionPane.PLAIN_MESSAGE);

            if (qtyStr == null || qtyStr.trim().isEmpty()) {
                return;
            }

            int enteredQty;
            try {
                enteredQty = Integer.parseInt(qtyStr.trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Invalid quantity entered!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (enteredQty <= 0) {
                JOptionPane.showMessageDialog(null, "Quantity must be greater than zero!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int index = getProductId(pid);
            if (index == -1) {
                if (enteredQty > availableQty) {
                    JOptionPane.showMessageDialog(null, "Only " + availableQty + " units available in stock!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                Object[] row = new Object[8];
                double amount = enteredQty * p.getOurPrice();
                amount += amount * p.getTax() / 100;
                p.setQuantity(enteredQty);
                p.setTotal(amount);

                row[0] = p.getProductId();
                row[1] = p.getProductName();
                row[2] = p.getProductPrice();
                row[3] = p.getOurPrice();
                row[4] = p.getProductCompany();
                row[5] = p.getQuantity();
                row[6] = p.getTax();
                row[7] = p.getTotal();
                tm.addRow(row);

                al.add(p);
                grTotal += p.getTotal();
            } else {
                ProductsPojo existingProduct = al.get(index);
                int newQty = existingProduct.getQuantity() + enteredQty;
                if (newQty > availableQty) {
                    JOptionPane.showMessageDialog(null, "Cannot add more than " + availableQty + " units!", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                double lineAmount = newQty * existingProduct.getOurPrice();
                lineAmount += lineAmount * existingProduct.getTax() / 100;

                existingProduct.setQuantity(newQty);
                existingProduct.setTotal(lineAmount);

                tm.setValueAt(newQty, index, 5);
                tm.setValueAt(lineAmount, index, 7);

                // recalc grand total
                grTotal = al.stream().mapToDouble(ProductsPojo::getTotal).sum();
            }

            lblGrandTotal.setText("Total: " + grTotal);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "DB Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    private int getProductId(String pid) {
        int index = -1;
        for (int i = 0; i < al.size(); i++) {
            ProductsPojo p = al.get(i);
            if (p.getProductId().equals(pid)) {
                index = i;
                break;
            }
        }
        return index;
    }
    }
