/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emart.gui;

import emart.pojo.UserProfile;

/**
 *
 * @author WELCOME
 */
public class ReceptionistOptionFrame extends javax.swing.JFrame {
    
  
    public ReceptionistOptionFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblUsername.setText(UserProfile.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        lblManageReceptionist = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnBillingSection = new javax.swing.JButton();
        btnVieworders = new javax.swing.JButton();
        lblSelectionOption = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emart/images/loginImage.png"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(320, 270));
        jLabel8.setMinimumSize(new java.awt.Dimension(320, 270));
        jLabel8.setPreferredSize(new java.awt.Dimension(320, 270));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(154, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setBackground(new java.awt.Color(204, 0, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setForeground(java.awt.Color.white);
        btnLogout.setText("Logout");
        btnLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.setContentAreaFilled(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 120, 41));

        lblManageReceptionist.setBackground(new java.awt.Color(255, 0, 0));
        lblManageReceptionist.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblManageReceptionist.setForeground(java.awt.Color.white);
        lblManageReceptionist.setText(" Receptionist Option Panel");
        jPanel1.add(lblManageReceptionist, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 330, 50));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 960, 120));

        jPanel6.setBackground(new java.awt.Color(154, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Welcome");

        lblUsername.setBackground(new java.awt.Color(204, 0, 0));
        lblUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsername.setForeground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 530, 60));

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 30, 22, -1));

        btnBillingSection.setBackground(new java.awt.Color(204, 0, 0));
        btnBillingSection.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBillingSection.setForeground(java.awt.Color.white);
        btnBillingSection.setText("Billing Section");
        btnBillingSection.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBillingSection.setContentAreaFilled(false);
        btnBillingSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillingSectionActionPerformed(evt);
            }
        });
        jPanel3.add(btnBillingSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 260, 110));

        btnVieworders.setBackground(new java.awt.Color(204, 0, 0));
        btnVieworders.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVieworders.setForeground(java.awt.Color.white);
        btnVieworders.setText("View Orders");
        btnVieworders.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVieworders.setContentAreaFilled(false);
        btnVieworders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewordersActionPerformed(evt);
            }
        });
        jPanel3.add(btnVieworders, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 260, 110));

        lblSelectionOption.setBackground(new java.awt.Color(197, 0, 0));
        lblSelectionOption.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSelectionOption.setForeground(java.awt.Color.white);
        lblSelectionOption.setText("Select Option");
        lblSelectionOption.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(lblSelectionOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -10, 90, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 400, 350));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emart/images/receptionist options.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 530, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        LoginFrame login = new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnViewordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewordersActionPerformed
        ViewOrdersFrame voframe = new ViewOrdersFrame();
        voframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewordersActionPerformed

    private void btnBillingSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillingSectionActionPerformed
        BillingFrame billframe=new BillingFrame();
        billframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBillingSectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }  catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
           ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReceptionistOptionFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBillingSection;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnVieworders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblManageReceptionist;
    private javax.swing.JLabel lblSelectionOption;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
