/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emart.gui;

import emart.dao.ProductsDAO;
import emart.pojo.ProductsPojo;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WELCOME
 */
public class UpdateItemFrame extends javax.swing.JFrame {
    
   

    DefaultTableModel tm;
    public UpdateItemFrame() {
        initComponents();
        this.setLocationRelativeTo(this);
        jtProductsList.setRowHeight(30);
        loadProductDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProductsList = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblEmpId = new javax.swing.JLabel();
        lblUsenName = new javax.swing.JLabel();
        lblUserId = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        txtOurPrice = new javax.swing.JTextField();
        txtProductPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtProductId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtProductCompany = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        jcTax = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        lblPassword1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdate.setBackground(new java.awt.Color(215, 0, 0));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate.setForeground(java.awt.Color.white);
        btnUpdate.setText("Update");
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 763, 113, 46));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Update Item Panel");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 450, 40));

        btnLogout.setBackground(new java.awt.Color(216, 0, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogout.setForeground(java.awt.Color.white);
        btnLogout.setText("LogOut");
        btnLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 30, 110, 40));

        btnBack.setBackground(new java.awt.Color(197, 0, 0));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(java.awt.Color.white);
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 107, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1296, 110));

        jtProductsList.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jtProductsList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Product Price", "Our Price", "CompanyName", "Quantity", "Tax"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtProductsList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProductsListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtProductsList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 1296, 370));

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmpId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmpId.setForeground(java.awt.Color.white);
        lblEmpId.setText("Product Id");
        jPanel3.add(lblEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 135, 28));

        lblUsenName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsenName.setForeground(java.awt.Color.white);
        lblUsenName.setText("Product Name");
        jPanel3.add(lblUsenName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 130, 27));

        lblUserId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUserId.setForeground(java.awt.Color.white);
        lblUserId.setText("Product Price");
        jPanel3.add(lblUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 120, 40));

        txtProductName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 220, 35));

        txtOurPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txtOurPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 120, 220, 35));

        txtProductPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txtProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 60, 220, 35));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product Company");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 160, 40));

        txtProductId.setEditable(false);
        txtProductId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txtProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 220, 35));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tax");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, 100, 20));

        txtProductCompany.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txtProductCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 220, 35));

        txtQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 220, 35));

        jcTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcTax.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0%", "5%", "18%", "28%", " " }));
        jcTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTaxActionPerformed(evt);
            }
        });
        jPanel3.add(jcTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 190, 220, 35));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantity");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 160, 40));

        lblPassword1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPassword1.setForeground(java.awt.Color.white);
        lblPassword1.setText("OurPrice");
        jPanel3.add(lblPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, 110, 30));

        jLabel2.setBackground(new java.awt.Color(204, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Add Item");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 160, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 1296, 240));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(!validateInputs())
       {
            JOptionPane.showMessageDialog(null,"Please fill all the fields");
            return;
       }
        try
        {
            int n=jcTax.getSelectedItem().toString().length();
            int tax=Integer.parseInt(jcTax.getSelectedItem().toString().substring(0,n-1));
            ProductsPojo p=new ProductsPojo();
            p.setProductId(txtProductId.getText().trim());
            p.setProductName(txtProductName.getText().trim());
            p.setProductCompany(txtProductCompany.getText().trim());
            p.setProductPrice(Double.parseDouble(txtProductPrice.getText().trim()));
            p.setOurPrice(Double.parseDouble(txtOurPrice.getText().trim()));
            p.setQuantity(Integer.parseInt(txtQuantity.getText().trim()));
            p.setTax(tax);
            boolean result=ProductsDAO.updateProduct(p);
            if(result)
            {
                JOptionPane.showMessageDialog(null,"Product update successfully!!");
                tm.setRowCount(0);
                loadProductDetails();
                return;             
            }
            JOptionPane.showMessageDialog(null,"Product update failed!!");
        }
        catch(SQLException ex)
          {
              JOptionPane.showMessageDialog(null, "DB Error: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
              ex.printStackTrace();
          }
         catch(NumberFormatException ex)
           {
             JOptionPane.showMessageDialog(null, "Plese pass numeric values!!","Error!", JOptionPane.ERROR_MESSAGE);
             ex.printStackTrace();
          }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        LoginFrame login=new LoginFrame();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        ManageStocksFrame msf = new ManageStocksFrame();
        msf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jtProductsListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProductsListMouseClicked
          int row=jtProductsList.getSelectedRow();
          txtProductId.setText(tm.getValueAt(row, 0).toString());
          txtProductName.setText(tm.getValueAt(row, 1).toString());
          txtProductPrice.setText(tm.getValueAt(row, 2).toString());
          txtOurPrice.setText(tm.getValueAt(row, 3).toString());
          txtProductCompany.setText(tm.getValueAt(row, 4).toString());
          txtQuantity.setText(tm.getValueAt(row, 5).toString());
          String tx=tm.getValueAt(row, 6).toString();
          jcTax.setSelectedItem(tx);
    }
    private boolean validateInputs()
    {
        return !(txtProductName.getText().isEmpty()||txtProductCompany.getText().isEmpty()|| txtProductPrice.getText().isEmpty()||txtOurPrice.getText().isEmpty()|| txtQuantity.getText().isEmpty());
              
    }//GEN-LAST:event_jtProductsListMouseClicked

    private void jcTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcTaxActionPerformed

  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
          ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UpdateItemFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jcTax;
    private javax.swing.JTable jtProductsList;
    private javax.swing.JLabel lblEmpId;
    private javax.swing.JLabel lblPassword1;
    private javax.swing.JLabel lblUsenName;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JTextField txtOurPrice;
    private javax.swing.JTextField txtProductCompany;
    private javax.swing.JTextField txtProductId;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtProductPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

    private void loadProductDetails() {
          try
        {
            List<ProductsPojo> al=ProductsDAO.getProductDetails();
            tm = (DefaultTableModel) jtProductsList.getModel();
            tm.setRowCount(0); 
            if(al.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "No products present in Stock");
                 return;
            }
            btnUpdate.setEnabled(true);
            Object [] rows=new Object[7];
            tm=(DefaultTableModel)jtProductsList.getModel();
            for(ProductsPojo p:al)
            {
                rows[0]=p.getProductId();
                rows[1]=p.getProductName();
                rows[2]=p.getProductPrice();
                rows[3]=p.getOurPrice();
                rows[4]=p.getProductCompany();
                rows[5]=p.getQuantity();
                rows[6]=p.getTax()+"%";
                tm.addRow(rows);  
                
            }
            
        }
        catch(SQLException ex)
        {
           JOptionPane.showMessageDialog(null, "DB Error: " + ex, "Error", JOptionPane.ERROR_MESSAGE);
           ex.printStackTrace();
        }
    }
}
